#!/bin/bash

echo "🚀 GitHub Push & Render Deployment Guide"
echo "========================================"
echo ""

# Check if we can push
echo "📡 Testing GitHub connection..."
git remote -v

echo ""
echo "🔑 To push to GitHub, choose one option:"
echo ""
echo "OPTION A - Use GitHub Personal Access Token (Recommended):"
echo "-----------------------------------------------------------"
echo "1. Go to: https://github.com/settings/tokens"
echo "2. Click 'Generate new token' → 'Generate new token (classic)'"
echo "3. Name: 'WhatsApp Bridge Deploy'"
echo "4. Select scopes: ✓ repo (full control)"
echo "5. Click 'Generate token'"
echo "6. Copy the token"
echo ""
echo "Then run:"
echo "  git push https://YOUR_TOKEN@github.com/KKaran64/whatsapp-ai-agent.git main"
echo ""
echo "OR set it permanently:"
echo "  git remote set-url origin https://YOUR_TOKEN@github.com/KKaran64/whatsapp-ai-agent.git"
echo "  git push origin main"
echo ""
echo ""
echo "OPTION B - Use SSH (if you have SSH key configured):"
echo "-----------------------------------------------------"
echo "  git remote set-url origin git@github.com:KKaran64/whatsapp-ai-agent.git"
echo "  git push origin main"
echo ""
echo ""
echo "OPTION C - Use GitHub CLI (if installed):"
echo "------------------------------------------"
echo "  gh auth login"
echo "  git push origin main"
echo ""
echo ""
echo "After successful push:"
echo "======================"
echo "✅ GitHub will have your code"
echo "✅ Render will auto-deploy (if configured)"
echo "✅ Wait 2-3 minutes for deployment"
echo ""
echo "Then:"
echo "1. Update Render environment variables:"
echo "   → https://dashboard.render.com"
echo "   → Select: whatsapp-ai-agent"
echo "   → Settings → Environment"
echo "   → Add: GROQ_API_KEY_2, GROQ_API_KEY_3, GROQ_API_KEY_4"
echo ""
echo "2. Test deployment:"
echo "   curl https://your-app.onrender.com/health"
echo ""
echo "3. Send test WhatsApp message: 'Hi'"
echo ""
